# Generated by Django 4.1.5 on 2023-01-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profession',
            options={'verbose_name': 'Профессия', 'verbose_name_plural': 'Профессии'},
        ),
        migrations.AddField(
            model_name='profession',
            name='image',
            field=models.ImageField(default=1, upload_to='../static/image'),
            preserve_default=False,
        ),
    ]
