# Generated by Django 4.1.5 on 2023-01-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_demand_alter_profession_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='salaryByYearForProfession',
            field=models.ImageField(upload_to='./static/image'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='vacancyByYearForProfession',
            field=models.ImageField(upload_to='./static/image'),
        ),
    ]
