# Generated by Django 4.1.5 on 2023-01-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_alter_demand_salarybyyearforprofession_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryByCities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.TextField(verbose_name='Город')),
                ('salary', models.TextField(verbose_name='Уровень зарплат')),
            ],
            options={
                'verbose_name': 'Город и зп',
                'verbose_name_plural': 'Города и их зп',
            },
        ),
        migrations.CreateModel(
            name='VacancyByCities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.TextField(verbose_name='Город')),
                ('vacancy', models.TextField(verbose_name='Доля вакансий')),
            ],
            options={
                'verbose_name': 'Город и доли вакансий',
                'verbose_name_plural': 'Города и доля вакансий',
            },
        ),
        migrations.AlterField(
            model_name='demand',
            name='salaryByYear',
            field=models.ImageField(upload_to='./static/image', verbose_name='График зп по годам'),
        ),
    ]
