# Generated by Django 4.1.5 on 2023-01-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_salarybycities_vacancybycities_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticsByYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('avgSalary', models.IntegerField(verbose_name='Средняя зп')),
                ('avgSalaryForProfession', models.IntegerField(verbose_name='Средняя зп c# программист')),
                ('countVacancy', models.IntegerField(verbose_name='Количество вакансий')),
                ('countVacancyForProfession', models.IntegerField(verbose_name='Количество вакансий c# программист')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистика по годам',
            },
        ),
        migrations.AlterModelOptions(
            name='demand',
            options={'verbose_name': 'График', 'verbose_name_plural': 'Графики'},
        ),
        migrations.AlterModelOptions(
            name='salarybycities',
            options={'verbose_name': 'География', 'verbose_name_plural': 'Города и их зп'},
        ),
        migrations.AlterModelOptions(
            name='vacancybycities',
            options={'verbose_name': 'География', 'verbose_name_plural': 'Города и доля вакансий'},
        ),
    ]
